
export const LOAD_CONNECTIONS_REQUEST = 'LOAD_CONNECTIONS_REQUEST';
export const LOAD_CONNECTIONS_SUCCESS = 'LOAD_CONNECTIONS_SUCCESS';
export const LOAD_CONNECTIONS_FAILURE = 'LOAD_CONNECTIONS_FAILURE';
